export default {
    defaultMargin: 12,
    defaultIconSize:36,
    defaultPadding:12,
    defaultSmallPadding:6,
    defaultSmallMargin:6,
    defaultHugePadding:18,
    defaultHugeMargin:18,
    defaultBorderRadius:6,
    defaultSmallBorderRadius:3,
    defaultHugeBorderRadius:18,
    defaultSmallBorderWidth:1,
    defaultBorderWidth:2,
    defaultHugeBorderWidth:4,
    defaultMarginBetweenItems:30,
    toolbarFontSize:24,
    hugeFontSize:18,
    defaultFontSize:14,
    smallFontSize:10
};